services:
    Aligent\BraintreeBundle\EventListener\PurchaseActionEventListener:
        tags:
            - { name: kernel.event_listener, event: aligent_braintree.payment_action, method: onPurchase }

    Aligent\BraintreeBundle\EventListener\AdvancedFraudEventListener:
        tags:
            - { name: kernel.event_listener, event: aligent_braintree.payment_action, method: onPurchase }
